[source]
type = "IMAGE"

[paths]
model = "assets/best.ascend310"
description = "assets/coco.txt"
drawScript = "lua/example.lua"

[[streams]]
id = "default"
source = "assets/bus.jpg"

[processing]
npuThreads = 1
cpuThreads = 1
