[source]
type = "VIDEO"

[paths]
model = "assets/best.rk3588"
description = "assets/coco.txt"
drawScript = "lua/example.lua"

[[streams]]
id = "default-00"
source = "rtsp://192.168.1.102:8554/2025/2025.mp4"

[[streams]]
id = "default-01"
source = "rtsp://192.168.1.102:8554/2025/2025.mp4"

[[streams]]
id = "default-02"
source = "rtsp://192.168.1.102:8554/2025/2025.mp4"

[[streams]]
id = "default-03"
source = "rtsp://192.168.1.102:8554/2025/2025.mp4"

[processing]
npuThreads = 4
cpuThreads = 8
fpsDecode = 30.0
fpsYolo = 10.0
mute = false
