[source]
type = "VIDEO"

[paths]
model = "assets/best.ascend310"
description = "assets/coco.txt"
drawScript = "lua/example.lua"

[[streams]]
id = "default-00"
source = "rtsp://127.0.0.1:8554/2025/2025.mp4"

#[[streams]]
#id = "default-01"
#source = "rtsp://127.0.0.1:8554/2025/2025.mp4"
#
#[[streams]]
#id = "default-02"
#source = "rtsp://127.0.0.1:8554/2025/2025.mp4"
#
#[[streams]]
#id = "default-03"
#source = "rtsp://127.0.0.1:8554/2025/2025.mp4"

[processing]
npuThreads = 2
cpuThreads = 6
fpsDecode = 30.0
fpsYolo = 10.0
mute = false
